ZONE_COLUMN = "departement"

DATE_COLUMN = "day"

TARGET = "fires"

TEST_SIZE = 0.2

RANDOM_STATE = 42

SELECTED_DEP = [
    "Aisne",
    "Alpes-Maritimes",
    "Ardèche",
    "Ariège",
    "Aude",
    "Aveyron",
    "Cantal",
    "Eure",
    "Eure-et-Loir",
    "Gironde",
    "Haute-Corse",
    "Hautes-Pyrénées",
    "Hérault",
    "Indre",
    "Landes",
    "Loiret",
    "Lozère",
    "Marne",
    "Oise",
    "Pyrénées-Atlantiques",
    "Pyrénées-Orientales",
    "Sarthe",
    "Somme",
    "Yonne",
]

TRAIN_SELECTED_DEP = [
    "Aisne",
    "Alpes-Maritimes",
    "Ardèche",
    "Ariège",
    "Aude",
    "Aveyron",
    "Cantal",
    "Eure",
    "Eure-et-Loir",
    "Gironde",
    "Haute-Corse",
    "Hautes-Pyrénées",
    "Hérault",
    "Indre",
    "Landes",
    "Loiret",
    "Lozère",
    "Marne",
    "Oise",
    "Pyrénées-Atlantiques",
    "Pyrénées-Orientales",
    "Sarthe",
    "Somme",
    "Yonne",
]

SELECTED_DEP_V0 = [
    "Pyrénées-Atlantiques",
    "Hautes-Pyrénées",
    "Ariège",
    "Haute-Corse",
    "Lozère",
    "Gard",
    "Hérault",
    "Bouches-du-Rhônes",
    "Pyrénées-Orientales",
    "Cantal",
    "Alpes-Maritimes",
    "Aveyron",
]

RF_PARAMS = {
    "n_estimators": 500,
    "min_samples_leaf": 10,
    "max_features": "sqrt",
    "class_weight": "balanced",
    "criterion": "gini",
    "random_state": 10,
    "n_jobs": -1,
}

XGB_PARAMS = {
    "max_depth": 10,
    "min_child_weight": 10,
    "eta": 0.01,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "objective": "binary:logistic",
    "eval_metric": ["logloss", "aucpr"],
}

MODEL_ERA5T_VARS = [
    "str_max",
    "str_mean",
    "ffmc_min",
    "str_min",
    "ffmc_mean",
    "str_mean_lag1",
    "str_max_lag1",
    "str_min_lag1",
    "isi_min",
    "ffmc_min_lag1",
    "isi_mean",
    "ffmc_mean_lag1",
    "ffmc_std",
    "ffmc_max",
    "isi_min_lag1",
    "isi_mean_lag1",
    "ffmc_max_lag1",
    "asn_std",
    "strd_max",
    "ssrd_min",
    "strd_mean",
    "isi_max",
    "strd_min",
    "d2m_min",
    "asn_min",
    "ssr_min",
    "ffmc_min_lag3",
    "ffmc_std_lag1",
    "lai_hv_mean_lag7",
    "str_max_lag3",
    "str_mean_lag3",
    "rsn_std_lag1",
    "fwi_mean",
    "ssr_mean",
    "ssrd_mean",
    "swvl1_mean",
    "rsn_std_lag3",
    "isi_max_lag1",
    "d2m_mean",
    "rsn_std",
]

MODEL_VARIABLES = [
    "ffmc_min",
    "str_mean",
    "str_min",
    "str_max",
    "ffmc_mean",
    "isi_min",
    "ffmc_min_lag1",
    "strd_mean",
    "isi_mean",
    "strd_min",
    "strd_max",
    "rsn_max",
    "ffmc_mean_lag1",
    "rsn_max_lag1",
    "str_mean_lag1",
    "str_min_lag1",
    "ffmc_std",
    "ffmc_max",
    "rsn_std",
    "str_max_lag1",
    "rsn_std_lag1",
    "rsn_max_lag3",
    "isi_min_lag1",
    "isi_mean_lag1",
    "ffmc_max_lag1",
    "rsn_std_lag3",
    "stl1_std_lag1",
    "stl1_std",
    "isi_max",
    "strd_min_lag1",
    "ffmc_min_lag3",
    "ffmc_std_lag1",
    "strd_mean_lag1",
    "rsn_mean_lag1",
    "fwi_mean",
    "isi_max_lag1",
    "sd_max",
    "strd_max_lag1",
    "rsn_mean",
    "snowc_std_lag7",
    "stl1_std_lag3",
]

LAG_COLUMNS = [
    'fwi_min', 'fwi_max', 'fwi_mean', 'fwi_std', 'ffmc_min', 'ffmc_max',
    'ffmc_mean', 'ffmc_std', 'dmc_min', 'dmc_max', 'dmc_mean', 'dmc_std',
    'dc_min', 'dc_max', 'dc_mean', 'dc_std', 'isi_min', 'isi_max', 'isi_mean',
    'isi_std', 'bui_min', 'bui_max', 'bui_mean', 'bui_std', 'dsr_min',
    'dsr_max', 'dsr_mean', 'dsr_std', 'asn_min', 'asn_max', 'asn_mean',
    'asn_std', 'd2m_min', 'd2m_max', 'd2m_mean', 'd2m_std', 'e_min', 'e_max',
    'e_mean', 'e_std', 'es_min', 'es_max', 'es_mean', 'es_std', 'fal_min',
    'fal_max', 'fal_mean', 'fal_std', 'lai_hv_min', 'lai_hv_max', 'lai_hv_mean',
    'lai_hv_std', 'lai_lv_min', 'lai_lv_max', 'lai_lv_mean', 'lai_lv_std',
    'lblt_min', 'lblt_max', 'lblt_mean', 'lblt_std', 'licd_min', 'licd_max',
    'licd_mean', 'licd_std', 'lict_min', 'lict_max', 'lict_mean', 'lict_std',
    'lmld_min', 'lmld_max', 'lmld_mean', 'lmld_std', 'lmlt_min', 'lmlt_max',
    'lmlt_mean', 'lmlt_std', 'lshf_min', 'lshf_max', 'lshf_mean', 'lshf_std',
    'ltlt_min', 'ltlt_max', 'ltlt_mean', 'ltlt_std', 'pev_min', 'pev_max',
    'pev_mean', 'pev_std', 'ro_min', 'ro_max', 'ro_mean', 'ro_std', 'rsn_min',
    'rsn_max', 'rsn_mean', 'rsn_std', 'sd_min', 'sd_max', 'sd_mean', 'sd_std',
    'sf_min', 'sf_max', 'sf_mean', 'sf_std', 'skt_min', 'skt_max', 'skt_mean',
    'skt_std', 'slhf_min', 'slhf_max', 'slhf_mean', 'slhf_std', 'smlt_min',
    'smlt_max', 'smlt_mean', 'smlt_std', 'sp_min', 'sp_max', 'sp_mean',
    'sp_std', 'src_min', 'src_max', 'src_mean', 'src_std', 'sro_min', 'sro_max',
    'sro_mean', 'sro_std', 'sshf_min', 'sshf_max', 'sshf_mean', 'sshf_std',
    'ssr_min', 'ssr_max', 'ssr_mean', 'ssr_std', 'ssrd_min', 'ssrd_max',
    'ssrd_mean', 'ssrd_std', 'ssro_min', 'ssro_max', 'ssro_mean', 'ssro_std',
    'stl1_min', 'stl1_max', 'stl1_mean', 'stl1_std', 'stl2_min', 'stl2_max',
    'stl2_mean', 'stl2_std', 'stl3_min', 'stl3_max', 'stl3_mean', 'stl3_std',
    'stl4_min', 'stl4_max', 'stl4_mean', 'stl4_std', 'str_min', 'str_max',
    'str_mean', 'str_std', 'strd_min', 'strd_max', 'strd_mean', 'strd_std',
    'swvl1_min', 'swvl1_max', 'swvl1_mean', 'swvl1_std', 'swvl2_min',
    'swvl2_max', 'swvl2_mean', 'swvl2_std', 'swvl3_min', 'swvl3_max',
    'swvl3_mean', 'swvl3_std', 'swvl4_min', 'swvl4_max', 'swvl4_mean',
    'swvl4_std', 't2m_min', 't2m_max', 't2m_mean', 't2m_std', 'tp_min',
    'tp_max', 'tp_mean', 'tp_std', 'tsn_min', 'tsn_max', 'tsn_mean', 'tsn_std',
    'u10_min', 'u10_max', 'u10_mean', 'u10_std', 'v10_min', 'v10_max',
    'v10_mean', 'v10_std'
]
